apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-deploy-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: db-pod
    spec:
      containers:
          - name: db-con
            image: postgres
            env:
              - name: POSTGRES_DB
                value: sparrow
              - name: POSTGRES_USER
                value: sparrow
              - name: POSTGRES_PASSWORD
                value: password
            ports:
              - containerPort: 5432
                name: db-port
